# Generated by Django 4.0.4 on 2022-06-16 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managers_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
