# Generated by Django 4.0.4 on 2022-06-21 08:32

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\artus\\Desktop\\Projects\\Django\\digital_marketplace\\static_cdn\\protected'), upload_to=products.models.download_media_location),
        ),
    ]
